config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views import defaults as default_views

from src.api.views import obtain_auth_key
from src.seo.sitemaps import (
    CompanySitemap,
    PublicBlogSitemap,
    QuestionSitemap,
    SuperinvestorSitemap,
    TermSitemap,
)
from src.general.views import Handler404

sitemaps = {
    "blogs": PublicBlogSitemap,
    "preguntas": QuestionSitemap,
    "empresas": CompanySitemap,
    "glosario": TermSitemap,
    "superinversores": SuperinvestorSitemap,
}

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path(
        settings.SECOND_ADMIN_URL, include("admin_honeypot.urls", namespace="admin_honeypot")
    ),
    path("", include("src.general.urls", namespace="general")),
    path("", include("src.web.urls", namespace="web")),
    path("", include("src.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("src.preguntas_respuestas.urls", namespace="preguntas_respuestas")),
    path("", include("src.escritos.urls", namespace="escritos")),
    path("", include("src.public_blog.urls", namespace="public_blog")),
    path("screener/", include("src.screener.urls", namespace="screener")),
    path("", include("src.super_investors.urls", namespace="super_investors")),
    path("", include("src.empresas.urls", namespace="empresas")),
    path("", include("src.socialmedias.urls", namespace="socialmedias")),
    path("", include("src.cartera.urls", namespace="cartera")),
    path("", include("src.seo.urls", namespace="seo")),
    path("", include("src.roboadvisor.urls", namespace="roboadvisor")),
    path("", include("src.business.urls", namespace="business")),
    path("", include("src.recsys.urls", namespace="recsys")),
    path("", include("src.emailing.urls", namespace="emailing")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("src.api.urls")),
    # DRF auth token
    path("api/obtener-clave/", obtain_auth_key),
]

handler403 = "src.general.views.handler403"
handler404 = Handler404.as_view()
handler500 = "src.general.views.handler500"

if settings.DEBUG:
    if "drf_spectacular" in settings.INSTALLED_APPS:
        from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

        urlpatterns += [
            path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
            path(
                "api/docs/",
                SpectacularSwaggerView.as_view(url_name="api-schema"),
                name="api-docs",
            ),
        ]

    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

src/screener/api/urls.py
from django.urls import path

from .views import (
    CompanyFODAListView,
    CompanyObservationFormView,
    CompanyScreenerView,
    get_company_news,
    get_company_price,
    get_company_valuation,
    medium_valuation_view,
    retreive_top_lists,
    retreive_yahoo_screener_info,
    return_similar_companies_screener,
    simple_valuation_view,
    suggest_list_search_companies,
)

urlpatterns = [
    path(
        "user-search-company/",
        suggest_list_search_companies,
        name="suggest_list_search_companies",
    ),
    path("valuations-list/", CompanyScreenerView.as_view(), name="valuation_list"),
    path("list-foda/<company_id>/", CompanyFODAListView.as_view(), name="list_foda"),
    path("get-company-news/<ticker>/", get_company_news, name="return_company_news"),
    path("retreive-company-price/<ticker>/", get_company_price, name="get_company_price"),
    path(
        "retreive-company-valuation/<ticker>/",
        get_company_valuation,
        name="get_company_valuation",
    ),
    path(
        "add-observation/",
        CompanyObservationFormView.as_view(),
        name="create_company_observation",
    ),
    path("screener-simple-valuation/", simple_valuation_view, name="simple_valuation_view"),
    path("screener-medium-valuation/", medium_valuation_view, name="medium_valuation_view"),
    path("retreive-top-lists/", retreive_top_lists, name="retreive_top_lists"),
    path(
        "retreive-yahoo-lists/<query>/",
        retreive_yahoo_screener_info,
        name="retreive_yahoo_screener_info",
    ),
    path(
        "return-similar-companies-screener/<sector_id>/<industry_id>/",
        return_similar_companies_screener,
        name="return_similar_companies_screener",
    ),
]

src/screener/urls.py
from django.urls import path

from .api.urls import urlpatterns
from .views import (
    AllYahooScreenersView,
    BuyCompanyInfo,
    CompanyDetailsView,
    CompanyLookUpView,
    CompanyScreenerInicioView,
    EtfDetailsView,
    EtfScreenerInicioView,
    ScreenerInicioView,
    YahooScreenerView,
)

# from src.screener.api.views import CompanyBaseAPIView

# import sys, inspect

# list_of_serializers = inspect.getmembers(sys.modules['src.empresas.api.serializers'],
# lambda member: inspect.isclass(member) and member.__module__ == 'src.empresas.api.serializers')


app_name = "screener"

urlpatterns = [
    path("", ScreenerInicioView.as_view(), name="screener_inicio"),
    path("empresas-de/<slug>/", CompanyScreenerInicioView.as_view(), name="companies_by"),
    path("etfs/", EtfScreenerInicioView.as_view(), name="etfs_inicio"),
    path("analisis-de/<ticker>/", CompanyDetailsView.as_view(), name="company"),
    path("analisis-etf/<ticker>/", EtfDetailsView.as_view(), name="etf"),
    path(
        "todas-las-mejores-listas/",
        AllYahooScreenersView.as_view(),
        name="all_yahoo_screeners",
    ),
    path("lista-de/<slug>/", YahooScreenerView.as_view(), name="yahoo_screener"),
    path("buscar-empresa/", CompanyLookUpView.as_view(), name="company_lookup"),
    path("buy-company-info/", BuyCompanyInfo.as_view(), name="buy_company_info"),
] + urlpatterns

# for serializer in list_of_serializers:
#     serial_name = serializer[0][:-10]
#     route = path(
#         f'{serial_name}',
#         CompanyBaseAPIView.as_view(serializer_class = serializer[1]),
#         name=f'{serial_name}'
#     )
#     urlpatterns.append(route)

src/screener/forms.py
from django import forms

from .models import UserCompanyObservation


class UserCompanyObservationForm(forms.ModelForm):
    observation = forms.CharField(
        label="Describe tu observación", widget=forms.Textarea(attrs={"id": "observation"})
    )

    class Meta:
        model = UserCompanyObservation
        fields = ["observation", "observation_type"]
        labels = {"observation_type": "Elige la categoría"}

src/screener/api/views.py
import json

from django.contrib.auth import get_user_model
from django.db.models import Q
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.generic import FormView, ListView
from rest_framework.response import Response

import yahooquery as yq

from src.empresas.models import Company
from src.empresas.outils.data_management.show.company_data import CompanyData
from src.empresas.outils.valuations import discounted_cashflow

from src.api.views import BasePublicAPIView
from ..forms import UserCompanyObservationForm
from ..models import (
    UserCompanyObservation,
    UserScreenerMediumPrediction,
    UserScreenerSimplePrediction,
    YahooScreener,
)

User = get_user_model()


class CompanyScreenerView(BasePublicAPIView):
    def get(self, *args, **kwargs):
        return Response({"data": [{"INTC": {"cool": 45}}, {"AMD": {"EUR": 45}}]})


class CompanyFODAListView(ListView):
    model = UserCompanyObservation
    template_name = "empresas/company_parts/foda/foda_parts.html"
    context_object_name = "foda_analysis"

    def get_queryset(self):
        return UserCompanyObservation.objects.filter(company__id=self.kwargs["company_id"])


def get_company_price(request, ticker):
    prices = CompanyData(Company.objects.get(ticker=ticker)).get_most_recent_price()
    return render(
        request,
        "headers/company_price.html",
        {
            "prices": prices,
        },
    )


def get_company_news(request, ticker):
    company = Company.objects.get(ticker=ticker)
    news = CompanyData(company).get_company_news()
    return render(
        request,
        "empresas/company_parts/resume/news.html",
        {
            "show_news": news,
        },
    )


def get_company_valuation(request, ticker):
    company = Company.objects.get(ticker=ticker)
    company_valuation = CompanyData(company).get_ratios_information()
    return render(
        request,
        "empresas/company_parts/valuations/response.html",
        {
            "company_valuation": company_valuation,
        },
    )


def retreive_yahoo_screener_info(request, query):
    yahoo = yq.Screener().get_screeners(query)
    context = {"yahoo": yahoo[query]["quotes"]}  # type: ignore
    return render(request, "yahoo-screeners/screener-data.html", context)


def retreive_top_lists(request):
    yahoo = yq.Screener().get_screeners(["most_actives", "day_gainers", "day_losers"], 5)
    extra = {"positive": "text-success", "negative": "text-danger"}
    url = "/screener/analisis-de/"
    day_gainers = {
        "title": "Mayor aumento de precio",
        "subtitle": "day_gainers",
        "slug": YahooScreener.objects.get(yq_name="day_gainers").slug,
        "extra": extra,
        "url": url,
        "data": yahoo["day_gainers"]["quotes"],  # type: ignore
    }
    day_losers = {
        "title": "Mayor disminución de precio",
        "subtitle": "day_losers",
        "slug": YahooScreener.objects.get(yq_name="day_losers").slug,
        "extra": extra,
        "url": url,
        "data": yahoo["day_losers"]["quotes"],  # type: ignore
    }
    most_actives = {
        "title": "Más activos",
        "subtitle": "most_actives",
        "slug": YahooScreener.objects.get(yq_name="most_actives").slug,
        "extra": extra,
        "url": url,
        "data": yahoo["most_actives"]["quotes"],  # type: ignore
    }

    gainers_actives_losers = [day_gainers, most_actives, day_losers]
    return render(
        request,
        "yahoo-screeners/top-lists.html",
        {
            "gainers_actives_losers": gainers_actives_losers,
        },
    )


def return_similar_companies_screener(request, sector_id, industry_id):
    return render(
        request,
        "empresas/company_parts/relationships/relations.html",
        {
            "similar_companies": Company.objects.get_similar_companies(sector_id, industry_id),
            "previous_ticker": request.GET.get("extra"),
        },
    )


class CompanyObservationFormView(FormView):
    form_class = UserCompanyObservationForm
    template_name = "empresas/company_parts/foda/foda_modal.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["company_ticker"] = self.request.GET["company_ticker"]
        return context

    def form_valid(self, form):
        company_ticker = self.request.POST["company_ticker"]
        user = User.objects.get_or_create_quick_user(self.request)  # type: ignore
        model = form.save()
        model.user = user
        company = Company.objects.get(ticker=company_ticker)
        model.company = company
        model.save(update_fields=["user", "company"])
        return HttpResponse(status=204, headers={"HX-Trigger": "refreshObservationsCompany"})


def suggest_list_search_companies(request):
    results = []
    if request.is_ajax():
        query = request.GET.get("term", "")
        companies_availables = Company.objects.filter(
            Q(name__icontains=query) | Q(ticker__icontains=query),
            no_incs=False,
            no_bs=False,
            no_cfs=False,
        ).only("name", "ticker")[:10]

        for company in companies_availables:
            result = f"{company.name} ({company.ticker})"
            results.append(result)

    return HttpResponse(json.dumps(results), "application/json")


def medium_valuation_view(request):
    is_ajax = request.headers.get("X-Requested-With") == "XMLHttpRequest"
    user = request.user if request.user.is_authenticated else None
    if is_ajax and request.method == "POST":
        data = json.load(request)

        opt_growth = float(data.get("complex_opt_growth", 0).replace(",", "."))
        neu_growth = float(data.get("complex_neu_growth", 0).replace(",", "."))
        pes_growth = float(data.get("complex_pes_growth", 0).replace(",", "."))
        company_id = data.get("company_id")
        opt_margin = float(data.get("complex_opt_margin", 0).replace(",", "."))
        neu_margin = float(data.get("complex_neu_margin", 0).replace(",", "."))
        pes_margin = float(data.get("complex_pes_margin", 0).replace(",", "."))
        opt_buyback = float(data.get("complex_opt_buyback", 0).replace(",", "."))
        neu_buyback = float(data.get("complex_neu_buyback", 0).replace(",", "."))
        pes_buyback = float(data.get("complex_pes_buyback", 0).replace(",", "."))
        opt_fcf_margin = float(data.get("complex_opt_fcf_margin", 0).replace(",", "."))
        neu_fcf_margin = float(data.get("complex_neu_fcf_margin", 0).replace(",", "."))
        pes_fcf_margin = float(data.get("complex_pes_fcf_margin", 0).replace(",", "."))

        the_company = Company.objects.get(id=company_id)
        latest_inc = the_company.inc_statements.latest()

        last_revenue = latest_inc.revenue
        average_shares_out = latest_inc.weighted_average_shares_outstanding

        UserScreenerMediumPrediction.objects.create(
            user=user,
            company=the_company,
            optimistic_growth=opt_growth,
            neutral_growth=neu_growth,
            pesimistic_growth=pes_growth,
            optimistic_margin=opt_margin,
            neutral_margin=neu_margin,
            pesimistic_margin=pes_margin,
            optimistic_buyback=opt_buyback,
            neutral_buyback=neu_buyback,
            pesimistic_buyback=pes_buyback,
            optimistic_fcf_margin=opt_fcf_margin,
            neutral_fcf_margin=neu_fcf_margin,
            pesimistic_fcf_margin=pes_fcf_margin,
        )

        opt_valuation = discounted_cashflow(
            last_revenue=last_revenue,
            revenue_growth=opt_growth,
            net_income_margin=opt_margin,
            fcf_margin=opt_fcf_margin,
            buyback=opt_buyback,
            average_shares_out=average_shares_out,
        )
        neu_valuation = discounted_cashflow(
            last_revenue=last_revenue,
            revenue_growth=neu_growth,
            net_income_margin=neu_margin,
            fcf_margin=opt_fcf_margin,
            buyback=neu_buyback,
            average_shares_out=average_shares_out,
        )
        pes_valuation = discounted_cashflow(
            last_revenue=last_revenue,
            revenue_growth=pes_growth,
            net_income_margin=pes_margin,
            fcf_margin=opt_fcf_margin,
            buyback=pes_buyback,
            average_shares_out=average_shares_out,
        )
        return JsonResponse(
            {
                "complex_opt_valuation": opt_valuation,
                "complex_neu_valuation": neu_valuation,
                "complex_pes_valuation": pes_valuation,
            }
        )


def simple_valuation_view(request):
    is_ajax = request.headers.get("X-Requested-With") == "XMLHttpRequest"
    user = request.user if request.user.is_authenticated else None
    if is_ajax and request.method == "POST":
        data = json.load(request)

        opt_growth = float(data.get("opt_grow", 0).replace(",", "."))
        neu_growth = float(data.get("neu_grow", 0).replace(",", "."))
        pes_growth = float(data.get("pes_grow", 0).replace(",", "."))
        company_id = data.get("comp")
        # buyback = float(data.get('buyback', 0).replace(',', '.'))

        the_company = Company.objects.get(id=company_id)
        latest_inc = the_company.inc_statements.latest()
        latest_margin = the_company.margins.latest()
        last_revenue = latest_inc.revenue
        average_shares_out = latest_inc.weighted_average_shares_outstanding
        net_income_margin = latest_margin.net_income_margin
        fcf_margin = latest_margin.fcf_margin
        buyback = the_company.growth_rates.latest().shares_buyback

        UserScreenerSimplePrediction.objects.create(
            user=user,
            company=the_company,
            optimistic_growth=opt_growth,
            neutral_growth=neu_growth,
            pesimistic_growth=pes_growth,
        )

src/screener/templates/yahoo-screeners/all-screeners.html
{% extends "bases/base_content.html" %}
{% load static i18n extra %}
{% block header %}{% include "headers/screeners.html" %}{% endblock header%}
{% block FirstCta %}
{% endblock FirstCta %}

{% block FirstContent %}
{% include "cta/buscador_empresas.html" %}
{% endblock FirstContent%}

{% block ListContent %}
<div class="row">
{% for screener in screeners %}
{% include "yahoo-screeners/screener-list.html" %}
{% endfor %}
</div>
{% endblock ListContent %}

src/screener/templates/yahoo-screeners/screener-data.html
{% load static i18n extra %}

<div class="card">
  <div class="card-header clearfix">
    <div class="float-start">
      {{now}}
    </div>
    <div class="float-end">
      <!-- <a>Ver más</a> -->
    </div>       
  </div>
  <div class="table-responsive">
      <table class="table table-hover">
        <tbody>
          {% for information in yahoo %}
            <tr>
              <th scope="row" style="width: 10px">
                  <a href="{% url 'screener:company' information.symbol %}{% utm stock_information.subtitle information.symbol %}"
                    class="name mb-0 text-sm">
                    {{information.symbol}}
                  </a>
                  <br>
                  <span class="name mb-0 text-xsm" style="font-size: 8px;">
                    {{information.shortName}}
                  </span>
              </th>
              <th>
                  Precio actual
                  <br>
              <span class="name mb-0 text-xsm">
                  {{information.regularMarketPrice|floatformat}} {{information.currency}}
              </span>
              </th>
              <th>
                  Cambio de precio
                  <br>
              <span class="name mb-0 text-xsm 
              {% if information.regularMarketChangePercent > 0 %}
              {{stock_information.extra.positive}}
              {% else %}
              {{stock_information.extra.negative}}
              {% endif %}">
                  {{information.regularMarketChangePercent|floatformat}} %
              </span>
              </th>
            </tr>
          {% endfor %}
        </tbody>
      </table>
  </div>
</div>

src/screener/templates/yahoo-screeners/screener-list.html
{% load static i18n extra %}
<div class="col-lg-6 col-md-12">
    <div class="card">
        <div class="card-body p-3">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex flex-column h-100">
                        <a href="{{screener.get_absolute_url}}{% utm 'list-screeners' screener.name %}">
                            <p class="h1 mb-1 pt-2 text-bold">
                                {{screener.name}}
                            </p>
                        </a>
                        
                        <div class="d-flex">
                            <a href="#" class="badge badge-info text-center mr-2">
                                <span class="font-weight-bolder">
                                    {{screener.asset_class_related}}
                                </span>
                            </a>
                        </div>
                        
                        <div class="mb-2 mt-2">
                            <a href="{{screener.get_absolute_url}}">
                                {{screener.description}}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/screener/templates/yahoo-screeners/screener.html
{% extends "bases/base_content.html" %}
{% load static i18n extra %}
{% block header %}{% include "headers/screeners.html" %}{% endblock header%}
{% block FirstCta %}
{% endblock FirstCta %}

{% block FirstContent %}
{% include "cta/buscador_empresas.html" %}
{% endblock FirstContent%}

{% block ListContent %}
<div class="card">
    <div class="card-header">
        <div class="text-center">
            <h2>{{screener.name}}</h2>
        </div>
    </div>
    <div class="card-body">
        {{screener.description}}
    </div>
</div>

<div hx-trigger="load" hx-get="{% url 'screener:retreive_yahoo_screener_info' screener.yq_name %}" hx-target="this">
    <div class="card">
        <div class="card-body">
            <div class="text-center">
                <div class="spinner-border" role="status">
                </div>
                Cargando...
            </div>
        </div>
    </div>
</div>
{% endblock ListContent %}

src/screener/templates/yahoo-screeners/top-lists.html
{% load static i18n extra %}
<div class="row">
  {% for stock_information in gainers_actives_losers %}
  <div class="col-xl-4 col-lg-12">
    <div class="card">
      <div class="card-header clearfix">
        <div class="float-start">
          {{stock_information.title}}
        </div>
        <div class="float-end">
          <a href="{% url 'screener:yahoo_screener' stock_information.slug %}{% utm 'visit-screener' stock_information.subtitle %}">
            Ver más
          </a>
        </div>        
      </div>
      <div class="table-responsive">
          <table class="table table-hover">
            <tbody>
              {% for information in stock_information.data %}
                <tr>
                  <th scope="row" style="width: 10px">
                      <a href="{% url 'screener:company' information.symbol %}{% utm 'screener' information.symbol %}"
                        class="name mb-0 text-sm">
                        {{information.symbol}}
                      </a>
                      <br>
                      <span class="name mb-0 text-xsm" style="font-size: 8px;">
                        {{information.shortName}}
                      </span>
                  </th>
                  <th>
                      Precio actual
                      <br>
                  <span class="name mb-0 text-xsm">
                      {{information.regularMarketPrice|floatformat}} {{information.currency}}
                  </span>
                  </th>
                  <th>
                      Cambio de precio
                      <br>
                  <span class="name mb-0 text-xsm 
                  {% if information.regularMarketChangePercent > 0 %}
                  {{stock_information.extra.positive}}
                  {% else %}
                  {{stock_information.extra.negative}}
                  {% endif %}">
                      {{information.regularMarketChangePercent|floatformat}} %
                  </span>
                  </th>
                </tr>
              {% endfor %}
            </tbody>
          </table>
      </div>
    </div>
  </div>
  {% endfor %}
</div>