config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views import defaults as default_views

from src.api.views import obtain_auth_key
from src.seo.sitemaps import (
    CompanySitemap,
    PublicBlogSitemap,
    QuestionSitemap,
    SuperinvestorSitemap,
    TermSitemap,
)
from src.general.views import Handler404

sitemaps = {
    "blogs": PublicBlogSitemap,
    "preguntas": QuestionSitemap,
    "empresas": CompanySitemap,
    "glosario": TermSitemap,
    "superinversores": SuperinvestorSitemap,
}

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path(
        settings.SECOND_ADMIN_URL, include("admin_honeypot.urls", namespace="admin_honeypot")
    ),
    path("", include("src.general.urls", namespace="general")),
    path("", include("src.web.urls", namespace="web")),
    path("", include("src.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("src.preguntas_respuestas.urls", namespace="preguntas_respuestas")),
    path("", include("src.escritos.urls", namespace="escritos")),
    path("", include("src.public_blog.urls", namespace="public_blog")),
    path("screener/", include("src.screener.urls", namespace="screener")),
    path("", include("src.super_investors.urls", namespace="super_investors")),
    path("", include("src.empresas.urls", namespace="empresas")),
    path("", include("src.socialmedias.urls", namespace="socialmedias")),
    path("", include("src.cartera.urls", namespace="cartera")),
    path("", include("src.seo.urls", namespace="seo")),
    path("", include("src.roboadvisor.urls", namespace="roboadvisor")),
    path("", include("src.business.urls", namespace="business")),
    path("", include("src.recsys.urls", namespace="recsys")),
    path("", include("src.emailing.urls", namespace="emailing")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("src.api.urls")),
    # DRF auth token
    path("api/obtener-clave/", obtain_auth_key),
]

handler403 = "src.general.views.handler403"
handler404 = Handler404.as_view()
handler500 = "src.general.views.handler500"

if settings.DEBUG:
    if "drf_spectacular" in settings.INSTALLED_APPS:
        from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

        urlpatterns += [
            path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
            path(
                "api/docs/",
                SpectacularSwaggerView.as_view(url_name="api-schema"),
                name="api-docs",
            ),
        ]

    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

src/business/urls.py
from django.urls import path

from .views import (
    CheckoutRedirectView,
    CreateCheckoutView,
    ProductDetailView,
    ProductsListView,
)
from .webhooks import stripe_webhook

app_name = "business"
urlpatterns = [
    path(
        "las-mejores-herramientas-para-invertir/",
        ProductsListView.as_view(),
        name="all_products",
    ),
    path(
        "la-mejor-herramienta-para-invertir-es/<slug>/",
        ProductDetailView.as_view(),
        name="product",
    ),
    path("create-checkout/<pk>/", CreateCheckoutView.as_view(), name="create_checkout"),
    path("pago-correcto/", CheckoutRedirectView.as_view(), name="order_success"),
    path("984dfgDFH68sDFg68s7fd", stripe_webhook, name="stripe_webhook"),
]

src/empresas/api/urls.py
from django.urls import path

from .views import (
    AllExchangesAPIView,
    BasicCompanyAPIView,
    CompanyBalanceSheetAPIView,
    CompanyCashflowStatementAPIView,
    CompanyIncomeStatementAPIView,
    CompleteCompanyAPIView,
    PublicCompanyAPIView,
)

urlpatterns = [
    path("companies/", PublicCompanyAPIView.as_view(), name="company-list"),
    path("companies/<str:ticker>/", PublicCompanyAPIView.as_view(), name="company-single"),
    # Currently using
    path("lista-exchanges/", AllExchangesAPIView.as_view()),
    path("empresa-completa/", CompleteCompanyAPIView.as_view()),
    path("empresa-basica/", BasicCompanyAPIView.as_view()),
    path("estado-resultados/", CompanyIncomeStatementAPIView.as_view()),
    path("balance-general/", CompanyBalanceSheetAPIView.as_view()),
    path("estado-flujo-efectivo/", CompanyCashflowStatementAPIView.as_view()),
]

src/empresas/urls.py
from django.urls import path

from .views import ExcelAPIBalance, ExcelAPICashflow, ExcelAPIIncome, companies_searcher

app_name = "empresas"
urlpatterns = [
    path("search-only-company/", companies_searcher, name="searcher_companies"),
    path(
        "company-information/excel-api/income", ExcelAPIIncome.as_view(), name="ExcelAPIIncome"
    ),
    path(
        "company-information/excel-api/balance",
        ExcelAPIBalance.as_view(),
        name="ExcelAPIBalance",
    ),
    path(
        "company-information/excel-api/cashflow",
        ExcelAPICashflow.as_view(),
        name="ExcelAPICashflow",
    ),
]

src/escritos/urls.py
from django.urls import path

from .views import (
    GlosarioView,
    ManageUserTermCorrectionDetailView,
    ManageUserTermCorrectionListView,
    TermCorrectionView,
    TermDetailsView,
)

app_name = "escritos"
urlpatterns = [
    path("diccionario-financiero/", GlosarioView.as_view(), name="glosario"),
    path("definicion/<slug>/", TermDetailsView.as_view(), name="single_term"),
    path("correction/<pk>", TermCorrectionView.as_view(), name="correction_term"),
    path(
        "users-corrections-to-review/",
        ManageUserTermCorrectionListView.as_view(),
        name="manage_all_corrections",
    ),
    path(
        "correction-to-review/<pk>/",
        ManageUserTermCorrectionDetailView.as_view(),
        name="manage_user_correction",
    ),
]

src/general/urls.py
from django.urls import path

from .api.views import CreateCommentView, VoteView
from .views import (
    ComingSoonview,
    MessagesTemplateview,
    NotificationsListView,
    delete_notification,
    search_results,
    suggest_list_search,
    update_favorites,
)

app_name = "general"
urlpatterns = [
    path(
        "create-comment/<url_encoded>/",
        CreateCommentView.as_view(),
        name="create_comment_view",
    ),
    path("create-vote/<url_encoded>/", VoteView.as_view(), name="create_vote_view"),
    path("suggestions-buscador/", suggest_list_search, name="searcher_suggestions"),
    path("buscador/", search_results, name="searcher"),
    path("update-favs/", update_favorites, name="update_favorites"),
    path("coming-soon/", ComingSoonview.as_view(), name="coming_soon"),
    path("tus-notificaciones/", NotificationsListView.as_view(), name="notifications_list"),
    path("delete-notif/<notif_id>/", delete_notification, name="notification_delete"),
    path("return-nav-messages/", MessagesTemplateview.as_view(), name="nav_messages"),
]

src/preguntas_respuestas/urls.py
from django.urls import path

from .views import (
    CreateQuestionView,
    QuestionDetailsView,
    QuestionsView,
    UpdateQuestionView,
    accept_answer,
    create_answer_view,
)

app_name = "preguntas_respuestas"
urlpatterns = [
    path("preguntas/", QuestionsView.as_view(), name="list_questions"),
    path("acceptar-answer/<question_id>/<answer_id>/", accept_answer, name="is_accepted"),
    path("question/<slug>/", QuestionDetailsView.as_view(), name="question"),
    path("create-question/", CreateQuestionView.as_view(), name="create_question"),
    path("update/<slug>/", UpdateQuestionView.as_view(), name="update_question"),
    path("create-answer/<slug>/", create_answer_view, name="create_answer"),
    # path('', CreateQuestionView.as_view(), name="update_question"),
    # path('', CreateQuestionView.as_view(), name="delete_question"),
]

src/screener/urls.py
from django.urls import path

from .api.urls import urlpatterns
from .views import (
    AllYahooScreenersView,
    BuyCompanyInfo,
    CompanyDetailsView,
    CompanyLookUpView,
    CompanyScreenerInicioView,
    EtfDetailsView,
    EtfScreenerInicioView,
    ScreenerInicioView,
    YahooScreenerView,
)

# from src.screener.api.views import CompanyBaseAPIView

# import sys, inspect

# list_of_serializers = inspect.getmembers(sys.modules['src.empresas.api.serializers'],
# lambda member: inspect.isclass(member) and member.__module__ == 'src.empresas.api.serializers')


app_name = "screener"

urlpatterns = [
    path("", ScreenerInicioView.as_view(), name="screener_inicio"),
    path("empresas-de/<slug>/", CompanyScreenerInicioView.as_view(), name="companies_by"),
    path("etfs/", EtfScreenerInicioView.as_view(), name="etfs_inicio"),
    path("analisis-de/<ticker>/", CompanyDetailsView.as_view(), name="company"),
    path("analisis-etf/<ticker>/", EtfDetailsView.as_view(), name="etf"),
    path(
        "todas-las-mejores-listas/",
        AllYahooScreenersView.as_view(),
        name="all_yahoo_screeners",
    ),
    path("lista-de/<slug>/", YahooScreenerView.as_view(), name="yahoo_screener"),
    path("buscar-empresa/", CompanyLookUpView.as_view(), name="company_lookup"),
    path("buy-company-info/", BuyCompanyInfo.as_view(), name="buy_company_info"),
] + urlpatterns

# for serializer in list_of_serializers:
#     serial_name = serializer[0][:-10]
#     route = path(
#         f'{serial_name}',
#         CompanyBaseAPIView.as_view(serializer_class = serializer[1]),
#         name=f'{serial_name}'
#     )
#     urlpatterns.append(route)

src/empresas/models/exchanges.py
from django.db.models import SET_NULL, CharField, ForeignKey, Model, PositiveIntegerField

from src.empresas import constants


class ExchangeOrganisation(Model):
    name = CharField(max_length=250, default="", blank=True)
    image = CharField(max_length=250, default="", blank=True)
    sub_exchange1 = CharField(max_length=250, default="", blank=True)
    sub_exchange2 = CharField(max_length=250, default="", blank=True)
    order = PositiveIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "Organisation exchange"
        verbose_name_plural = "Organisation exchanges"
        db_table = "assets_exchanges_organisations"

    def __str__(self) -> str:
        return self.name or str(self.pk)


class Exchange(Model):
    exchange_ticker = CharField(max_length=30, default="", blank=True)
    exchange = CharField(max_length=250, default="", blank=True)
    country = ForeignKey("countries.Country", on_delete=SET_NULL, null=True, blank=True)
    main_org = ForeignKey(ExchangeOrganisation, on_delete=SET_NULL, null=True, blank=True)
    data_source = CharField(
        max_length=100, choices=constants.DATA_SOURCES, default=constants.DATA_SOURCE_FINPREP
    )

    class Meta:
        ordering = ["-exchange_ticker"]
        verbose_name = "Exchange"
        verbose_name_plural = "Exchanges"
        db_table = "assets_exchanges"

    def __str__(self):
        return self.exchange_ticker or str(self.pk)

    @property
    def num_emps(self):
        return self.companies.all().count()

src/empresas/models/finnhub.py
from django.db.models import SET_NULL, ForeignKey, JSONField, Model

from src.empresas.models import Company


class StatementsFinnhub(Model):
    company = ForeignKey(Company, on_delete=SET_NULL, null=True, blank=True)
    financials = JSONField(default=dict)

    class Meta:
        verbose_name = "Finnhub All Statements"
        verbose_name_plural = "Finnhub All Statements"
        db_table = "assets_companies_all_statements_finnhub"

    def __str__(self):
        return self.company.ticker

src/screener/forms.py
from django import forms

from .models import UserCompanyObservation


class UserCompanyObservationForm(forms.ModelForm):
    observation = forms.CharField(
        label="Describe tu observación", widget=forms.Textarea(attrs={"id": "observation"})
    )

    class Meta:
        model = UserCompanyObservation
        fields = ["observation", "observation_type"]
        labels = {"observation_type": "Elige la categoría"}

src/empresas/api/views.py
from src.api.pagination import StandardResultPagination
from src.api.views import BaseAPIView, BasePublicAPIView
from src.empresas.api.serializers import (
    BalanceSheetSerializer,
    BasicCompanySerializer,
    CashflowStatementSerializer,
    CompanySerializer,
    ExchangeSerializer,
    IncomeStatementSerializer,
)
from src.empresas.models import (
    BalanceSheet,
    CashflowStatement,
    Company,
    Exchange,
    IncomeStatement,
)


class PublicCompanyAPIView(BasePublicAPIView):
    many_serializer_class = BasicCompanySerializer
    single_serializer_class = CompanySerializer
    many_queryset = Company.objects.select_related_information().all()
    single_queryset = Company.objects.api_query().all()
    lookup_field = "ticker"


class AllExchangesAPIView(BaseAPIView):
    serializer_class = ExchangeSerializer
    queryset = (Exchange.objects.all, True)
    pagination_class = StandardResultPagination
    model_to_track = "ignore"


class BasicCompanyAPIView(BaseAPIView):
    serializer_class = BasicCompanySerializer
    url_parameters = ["ticker"]
    model_to_track = Company


class CompleteCompanyAPIView(BaseAPIView):
    serializer_class = CompanySerializer
    queryset = (Company.objects.fast_full, False)
    url_parameters = ["ticker"]
    model_to_track = Company


class CompanyIncomeStatementAPIView(BaseAPIView):
    serializer_class = IncomeStatementSerializer
    limited = True
    url_parameters = ["ticker"]
    queryset = (IncomeStatement.objects.yearly_exclude_ttm, True)
    fk_lookup_model = "company__ticker"
    model_to_track = Company


class CompanyBalanceSheetAPIView(BaseAPIView):
    serializer_class = BalanceSheetSerializer
    limited = True
    queryset = (BalanceSheet.objects.yearly_exclude_ttm, True)
    url_parameters = ["ticker"]
    fk_lookup_model = "company__ticker"
    model_to_track = Company


class CompanyCashflowStatementAPIView(BaseAPIView):
    serializer_class = CashflowStatementSerializer
    limited = True
    queryset = (CashflowStatement.objects.yearly_exclude_ttm, True)
    url_parameters = ["ticker"]
    fk_lookup_model = "company__ticker"
    model_to_track = Company

src/empresas/views.py
import json

from typing import List

from django.db.models import Q
from django.http.response import HttpResponse

from .api.serializers import (
    ExcelBalanceSheetSerializer,
    ExcelCashflowStatementSerializer,
    ExcelIncomeStatementSerializer,
)
from .api.views import BaseAPIView
from .models import BalanceSheet, CashflowStatement, Company, IncomeStatement


class Suggestor:
    @classmethod
    def suggest_companies(cls, query: str) -> List[str]:
        companies_availables = Company.objects.filter(
            Q(name__icontains=query) | Q(ticker__icontains=query),
            no_incs=False,
            no_bs=False,
            no_cfs=False,
        )[:10]
        return [f"{company.name} [{company.ticker}]" for company in companies_availables]

    @classmethod
    def companies_searcher(cls, request) -> HttpResponse:
        query = request.GET.get("term", "")
        results = Suggestor.suggest_companies(query)
        return HttpResponse(json.dumps(results), "application/json")


def companies_searcher(request) -> HttpResponse:
    return Suggestor.companies_searcher(request)


class BaseExcelAPIView(BaseAPIView):
    """
    Used to share across API endpoints that serve the Inteligent Excel
    It will lookup for "ticker" in the url parameters and will look for the company's ticker
    """

    url_parameters = ["ticker"]
    fk_lookup_model = "company__ticker"
    limited = True
    is_excel = True
    model_to_track = "Company"


class ExcelAPIIncome(BaseExcelAPIView):
    """
    Used to serves the Inteligent Excel with the company's income statements
    """

    queryset = (IncomeStatement.objects.yearly, True)
    serializer_class = ExcelIncomeStatementSerializer


class ExcelAPIBalance(BaseExcelAPIView):
    """
    Used to serves the Inteligent Excel with the company's balance sheets
    """

    queryset = (BalanceSheet.objects.yearly, True)
    serializer_class = ExcelBalanceSheetSerializer


class ExcelAPICashflow(BaseExcelAPIView):
    """
    Used to serves the Inteligent Excel with the company's cashflow statements
    """

    queryset = (CashflowStatement.objects.yearly, True)
    serializer_class = ExcelCashflowStatementSerializer

src/screener/templates/empresas/company_detail.html
{% extends "bases/base_content.html" %}
{% load static extra %}

{% block TopHeader %}
{% include "headers/empresa_header.html" %}
{% endblock TopHeader%}
{% block MainContent %}
{% with the_company_financials=complete_info %}
<script>let hasBought = {% if has_bought %} true {% else %} false {% endif %}</script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js" 
integrity="sha512-UXumZrZNiOwnTcZSHLOfcTs0aos2MzBWHXOHOuB0J/R44QB0dwY5JgfbvljXcklVf65Gc4El6RjZ+lnwd2az2g==" 
crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-zoom/1.2.0/chartjs-plugin-zoom.min.js" 
integrity="sha512-TT0wAMqqtjXVzpc48sI0G84rBP+oTkBZPgeRYIOVRGUdwJsyS3WPipsNh///ay2LJ+onCM23tipnz6EvEy2/UA==" 
crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="{% static 'general/assets/js/screener.js' %}"></script>

<style>
.fixedTable th:first-child, td:first-child{
  position:sticky;
  left:0px;
  background-color:#fff;
}
::-webkit-scrollbar {
  width: 9px;
  height: 9px;
}

/* Track */
::-webkit-scrollbar-track {
  box-shadow: inset 0 0 5px grey;
  border-radius: 10px;
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: rgb(121, 121, 121);
  border-radius: 10px;
}
.chart-canvas{height: 600px !important;}
</style>
<div class="col-12">
    <div class="tab-content" id="pills-tabContent">
      <!-- resume tab -->
      <div class="tab-pane fade show active" id="pills-resume" role="tabpanel" aria-labelledby="pills-resume-tab">
        {% include "empresas/company_parts/resume/response.html" %}
      </div>
      <!-- First tab -->
      <div class="tab-pane fade" id="pills-income" role="tabpanel" aria-labelledby="pills-income-tab"> 
        {% include "empresas/company_parts/income_statement/income_statement.html" %}
      </div>
      <!-- Second tab -->
      <div class="tab-pane fade" id="pills-balancesh" role="tabpanel" aria-labelledby="pills-balancesh-tab">
        {% include "empresas/company_parts/balance_sheet/balance_sheet.html" %}
      </div>
      <!-- Third tab -->
      <div class="tab-pane fade" id="pills-cashflow" role="tabpanel" aria-labelledby="pills-cashflow-tab">
        {% include "empresas/company_parts/cashflow_statement/cashflow_statement.html" %}
      </div>
      <!-- ratios tab -->
      <div class="tab-pane fade" id="pills-ratios" role="tabpanel" aria-labelledby="pills-ratios-tab">
          {% include "empresas/company_parts/ratios/ratios.html" %}
      </div>
      <!-- other ratios tab -->
      <div class="tab-pane fade" id="pills-othervaluations" role="tabpanel" aria-labelledby="pills-othervaluations-tab">            
        {% include "empresas/company_parts/ratios/other_ratios.html" %}
      </div>
      <!-- foda tab -->
      <div class="tab-pane fade" id="pills-foda" role="tabpanel" aria-labelledby="pills-foda-tab">             
      {% include "empresas/company_parts/foda/foda.html" %}
      </div>
        <!-- valuations tab -->
      <div class="tab-pane fade" id="pills-valuations" role="tabpanel" aria-labelledby="pills-valuations-tab">             
          {% include "empresas/company_parts/valuations/valuations.html" %}
      </div>  
      <!-- predictions tab -->
      <div class="tab-pane fade" id="pills-predictions" role="tabpanel" aria-labelledby="pills-predictions-tab">    
        {% include "empresas/company_parts/predictions/predictions.html" %}
      </div>               
      <!-- superinvestors tab -->
      <div class="tab-pane fade" id="pills-superinvestors" role="tabpanel" aria-labelledby="pills-superinvestors-tab">
        {% include "empresas/company_parts/relationships/superinvestors_relateds.html" %}
      </div>
      
      <div class="tab-pane fade" id="pills-relations" role="tabpanel" aria-labelledby="pills-relations-tab">
        {% include "empresas/company_parts/relationships/wait-relations.html" %}
      </div>
    </div>
</div>
{% endwith %}
<div class="modal fade" id="NecesitasMembresiaModal" tabindex="-1" 
  role="dialog" aria-labelledby="NecesitasMembresiaModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-success modal-dialog-centered modal-xl" role="document">
      <div class="modal-content bg-gradient-success">
          <div class="modal-header">
              <h6 class="modal-title" id="modal-title-notification">Descubre toda la historia de la empresa</h6>
              <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
              </button>
          </div>
          {% if request.user.is_authenticated and request.user.user_profile.creditos >= 10 %}
          {% include "modals/buy-company-info.html" %}
          {% else %}
          <div class="modal-body">
            <p>
              <b>No tienes suficientes créditos.
                <br>
                Los créditos son monedas que puedes usar en la web para tener accesos privilegiados, puedes conseguir más créditos:                    
                <ul>
                    <li>Aportando respuestas</li>
                    <li>Haciendo preguntas</li>
                    <li>Colaborando en el glosario</li>
                    <li>Contribuyendo en las empresas</li>
                    <li>Adquiriendo créditos</li>
                </ul>
              </b>
            </p>
            <div class="col-12">
                <a class="btn btn-youtube" href="{% url 'preguntas_respuestas:list_questions' %}{% utm 'screener' the_company.ticker %}" >Preguntas</a>
                <a class="btn btn-slack" href="{% url 'escritos:glosario' %}{% utm 'screener' the_company.ticker %}" >Glosario</a>
                <a class="btn btn-danger" href="{% url 'screener:screener_inicio' %}{% utm 'screener' the_company.ticker %}" >Empresas</a>
                <a class="btn btn-danger" href="{% url 'business:all_products' %}{% utm 'screener' the_company.ticker %}" >Créditos</a>
            </div>
        </div>
          {% endif %}          
      </div>
  </div>
</div>
{% endblock MainContent %}
{% block javascript %}
{{ block.super }}
<script>
;(function () {
  const modal = new bootstrap.Modal(document.getElementById("CompanyObservationModal"))

  htmx.on("htmx:afterSwap", (e) => {
    // Response targeting #dialog => show the modal
    if (e.detail.target.id == "dialog") {
      modal.show()
    }
  })

  htmx.on("htmx:beforeSwap", (e) => {
    // Empty response targeting #dialog => hide the modal
    if (e.detail.target.id == "dialog" && !e.detail.xhr.response) {
      modal.hide()
      e.detail.shouldSwap = false
    }
  })

  // Remove dialog content after hiding
  htmx.on("hidden.bs.modal", () => {
    document.getElementById("dialog").innerHTML = ""
  })

})()

</script>
{% endblock javascript %}

src/screener/templates/empresas/company_inicio.html
{% extends "bases/base_content.html" %}
{% load static extra humanize i18n %}
{% block header %}{% include "headers/inicio_header.html" %}{% endblock header%}

{% block FirstCta %}{% include "cta/empresa_inicio.html" %}{% endblock FirstCta %}

{% block FirstContent %}
{% for empresa in empresas %}
<div class="col-xl-4 col-lg-6 col-sm-12">
    <div class="card">
        <!-- Card body -->
        <div class="card-body">
           <div class="row align-items-center">
              <div class="col-auto">
                 <!-- Avatar -->
                 <a href="{% url 'screener:company' empresa.ticker %}{% utm 'market' empresa.ticker %}" class="avatar avatar-xl rounded-circle">
                 <img alt="{{empresa.ticker}}" src="{{empresa.image}}">
                 </a>
              </div>
              <div class="col ml--2">
                 <h4 class="mb-0">
                    <a href="{% url 'screener:company' empresa.ticker %}" >{{empresa.name}}</a>
                 </h4>
                 <p class="text-sm text-muted mb-0">{{empresa.description|truncatewords:"25"}}</p>
              </div>
              <div class="col-auto">
                 <button type="button" class="btn btn-sm btn-success mb-1" 
                     onclick="AddToFav('{{empresa.ticker}}', '{{empresa.id}}')" type="submit" id="button-favs-{{empresa.id}}">
                     <i class="fa fa-star" aria-hidden="true"></i>
                     Favoritos
                  </button>

                 <br>
                 <!-- <button type="button" class="btn btn-sm btn-primary mb-1">Añadir cartera</button>
                 <br> -->
                 <a href="{% url 'screener:company' empresa.ticker %}{% utm 'market' empresa.ticker %}" type="button" class="btn btn-sm btn-primary">
                  <i class="fa fa-eye" aria-hidden="true"></i>
                    Visitar
                  </a>
                 
              </div>
           </div>
        </div>
     </div>
</div>
{% endfor %}
 <nav aria-label="Page navigation">
   <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
         <a class="page-link" href="?page=1">1</a>
      </li>
     <li class="page-item">
       <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
         <span aria-hidden="true">&laquo;</span>
       </a>
     </li>
     {% endif %}
     {% if page_obj.number != 1 %}
     <li class="page-item">
      <a href="?page={{ page_obj.number|add:-1 }}" class="page-link">{{ page_obj.number|add:-1 }}</a>
    </li>
    {% endif %}
      <li class="page-item active" aria-current="page">
         <span class="page-link">{{ page_obj.number }}</span>
      </li>
      <li class="page-item">
         <a href="?page={{ page_obj.number|add:1 }}" class="page-link">{{ page_obj.number|add:1 }}</a>
       </li>
     {% if page_obj.has_next %}
     <li class="page-item">
       <a class="page-link" href="?page={{ page_obj.next_page_number }}">
         <span aria-hidden="true">&raquo;</span>
       </a>
     </li>
     <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Último</a>
      </li>
     {% endif %}
   </ul>
 </nav>
 <script>
   const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
   
   function AddToFav(ticker, id){
 
     event.preventDefault(); // <---- Add this line
     $.ajax({
       url: '{% url "general:update_favorites" %}',
       type: "POST",
       dataType: "json",
       data: JSON.stringify({ticker: ticker,}),
       headers: {
       "X-Requested-With": "XMLHttpRequest",
       'X-CSRFToken': csrftoken,
       
     },
     success: (response) => {
         let buttonStock = document.getElementById("button-favs-"+id)
         if (response.is_favorite === true){
           buttonStock.className ='btn btn-sm btn-success mb-1'}
         else {
           buttonStock.className ='btn btn-sm btn-outline-success mb-1'}
           }
     });
   };
 </script>
{% endblock FirstContent%}