config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views import defaults as default_views

from src.api.views import obtain_auth_key
from src.seo.sitemaps import (
    CompanySitemap,
    PublicBlogSitemap,
    QuestionSitemap,
    SuperinvestorSitemap,
    TermSitemap,
)
from src.general.views import Handler404

sitemaps = {
    "blogs": PublicBlogSitemap,
    "preguntas": QuestionSitemap,
    "empresas": CompanySitemap,
    "glosario": TermSitemap,
    "superinversores": SuperinvestorSitemap,
}

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path(
        settings.SECOND_ADMIN_URL, include("admin_honeypot.urls", namespace="admin_honeypot")
    ),
    path("", include("src.general.urls", namespace="general")),
    path("", include("src.web.urls", namespace="web")),
    path("", include("src.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("src.preguntas_respuestas.urls", namespace="preguntas_respuestas")),
    path("", include("src.escritos.urls", namespace="escritos")),
    path("", include("src.public_blog.urls", namespace="public_blog")),
    path("screener/", include("src.screener.urls", namespace="screener")),
    path("", include("src.super_investors.urls", namespace="super_investors")),
    path("", include("src.empresas.urls", namespace="empresas")),
    path("", include("src.socialmedias.urls", namespace="socialmedias")),
    path("", include("src.cartera.urls", namespace="cartera")),
    path("", include("src.seo.urls", namespace="seo")),
    path("", include("src.roboadvisor.urls", namespace="roboadvisor")),
    path("", include("src.business.urls", namespace="business")),
    path("", include("src.recsys.urls", namespace="recsys")),
    path("", include("src.emailing.urls", namespace="emailing")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("src.api.urls")),
    # DRF auth token
    path("api/obtener-clave/", obtain_auth_key),
]

handler403 = "src.general.views.handler403"
handler404 = Handler404.as_view()
handler500 = "src.general.views.handler500"

if settings.DEBUG:
    if "drf_spectacular" in settings.INSTALLED_APPS:
        from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

        urlpatterns += [
            path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
            path(
                "api/docs/",
                SpectacularSwaggerView.as_view(url_name="api-schema"),
                name="api-docs",
            ),
        ]

    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

src/business/urls.py
from django.urls import path

from .views import (
    CheckoutRedirectView,
    CreateCheckoutView,
    ProductDetailView,
    ProductsListView,
)
from .webhooks import stripe_webhook

app_name = "business"
urlpatterns = [
    path(
        "las-mejores-herramientas-para-invertir/",
        ProductsListView.as_view(),
        name="all_products",
    ),
    path(
        "la-mejor-herramienta-para-invertir-es/<slug>/",
        ProductDetailView.as_view(),
        name="product",
    ),
    path("create-checkout/<pk>/", CreateCheckoutView.as_view(), name="create_checkout"),
    path("pago-correcto/", CheckoutRedirectView.as_view(), name="order_success"),
    path("984dfgDFH68sDFg68s7fd", stripe_webhook, name="stripe_webhook"),
]

src/preguntas_respuestas/urls.py
from django.urls import path

from .views import (
    CreateQuestionView,
    QuestionDetailsView,
    QuestionsView,
    UpdateQuestionView,
    accept_answer,
    create_answer_view,
)

app_name = "preguntas_respuestas"
urlpatterns = [
    path("preguntas/", QuestionsView.as_view(), name="list_questions"),
    path("acceptar-answer/<question_id>/<answer_id>/", accept_answer, name="is_accepted"),
    path("question/<slug>/", QuestionDetailsView.as_view(), name="question"),
    path("create-question/", CreateQuestionView.as_view(), name="create_question"),
    path("update/<slug>/", UpdateQuestionView.as_view(), name="update_question"),
    path("create-answer/<slug>/", create_answer_view, name="create_answer"),
    # path('', CreateQuestionView.as_view(), name="update_question"),
    # path('', CreateQuestionView.as_view(), name="delete_question"),
]

src/users/urls.py
from django.urls import path

from .views import (
    UpdateProfileView,
    UserDetailView,
    UserHistorialView,
    UserPublicProfileDetailView,
    invitation_view,
)

app_name = "users"
urlpatterns = [
    path("invitacion/<invitation_code>", invitation_view, name="invitation"),
    path("~update/", UpdateProfileView.as_view(), name="update"),
    path("inicio/", UserDetailView.as_view(), name="user-detail-view"),
    path(
        "perfil/<username>/", UserPublicProfileDetailView.as_view(), name="user_public_profile"
    ),
    path("historial-perfil/<slug>", UserHistorialView.as_view(), name="user_historial"),
]

src/web/templates/explorar/api_documentation.html
{% extends "bases/base_content.html" %}
{% load static i18n extra %}

{% block sidebar %}
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
      <!-- Brand -->
        <div class="sidenav-header  d-flex align-items-center">
            
            <a class="navbar-brand text-right">
            <img src="{% static 'general/assets/img/general/finanzaseinversiones.WebP' %}" height="40" class="navbar-brand-img" alt="Logo">
            </a>

            <div class=" ml-auto ">
            <!-- Sidenav toggler -->
            <div class="sidenav-toggler d-none d-xl-block" data-action="sidenav-unpin" data-target="#sidenav-main">
                <div class="sidenav-toggler-inner">
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
                </div>
            </div>
            </div>
        </div>

        <div class="navbar-inner">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Nav items -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        {% if request.user.is_anonymous %}
                        <a class="nav-link active" href="{% url 'preguntas_respuestas:list_questions' %}{% utm 'sidebar' 'Inicio' %}">
                            {% else %}
                        <a class="nav-link active" href="{% url 'users:user-detail-view' %}{% utm 'sidebar' 'Inicio' %}">
                            {% endif %}
                            <i class="fas fa-home text-primary"></i>
                            <span class="nav-link-text">Inicio</span>
                        </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'business:all_products' %}{% utm 'sidebar' 'Herramientas' %}">
                        <i class="fa-solid fa-briefcase text-primary"></i>
                        <span class="nav-link-text">Herramientas</span>
                      </a>
                    </li>
                    {% for category in endpoints_categories %}
                    <hr class="my-3">
                    <h6 class="navbar-heading pl-4 text-muted">
                        <span class="docs-normal">{{category.title}}</span>
                    </h6>
                        {% for endpoint in category.endpoints.all %}
                        <li class="nav-item">
                            <a class="nav-link" href="#{{endpoint.slug}}">
                              {{category.icon|safe}}
                            <span class="nav-link-text">
                                {{endpoint.title}}
                                {% if endpoint.is_new %}
                                <span class="badge badge-pill badge-xs bg-info">Nuevo</span>
                                {% elif endpoint.is_premium %}
                                <span class="badge badge-pill badge-xs bg-yellow">Premium</span>
                                {% elif endpoint.is_deprecated %}
                                <span class="badge badge-pill badge-xs bg-danger">Deprecated</span>
                                {% endif %}
                            </span>
                            </a>
                        </li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</nav>
{% endblock sidebar %}

{% block header %}{% include "explorar/header/api.html" %}{% endblock header%}

{% block FirstCtaContent %}
{% include "explorar/cta/first.html" %}
{% endblock FirstCtaContent %}
{% block FirstContent %}
<h1 class="mt-4"><b>Guía de utilización</b></h1>
      <p>
        La API de Inversiones & Finanzas está basada en REST, con respuestas basadas en los códigos usuales HTTP y la información presentada en JSON.
      </p>
      <p>
        El url de base de la API es: https://inversionesyfinanzas.xyz/
      </p>
        <br>
        <p>
        Es posible que la API evolucione con el tiempo y algunos endpoints se vuelvan obsoletos, en caso de ser así avisaremos por email con antelación.
      </p>
        <br>
        <p>
        A la hora de utilizar la API <b>es obligatorio</b> hacer referencia a Inversiones & Finanzas añadiendo el siguiente enlace: 
        <input class="form-control" readonly value='<a href="https://inversionesyfinanzas.xyz">Datos provenientes de Inversiones & Finanzas</a>'>
      </p>
        <br>
      <p>
        En caso de tener alguna duda o sugerencia puedes contactarnos a <b>contacto[at]inversionesyfinanzas.xyz</b>
      </p>
      <br>
      <p>
        {% if user.is_authenticated %}
          {% if show_api_key == True %}
            <button class="form-control" id="prog_api" style="background-color: #dfdfdfaf;word-break: break-all;" onclick="copyToClipboard('#prog_api')"
                data-bs-toggle="popover" data-bs-placement="top" data-bs-content="Copiar">{{key}}</button>
          {% else %}
          <a href="#!" data-bs-toggle="modal" data-bs-target="#APIKeyModal" class="form-control" readonly>Obtener clave API</a>
          {% endif %}
        {% else %}
        <a href="{% url 'users:user-detail-view' %}{% utm 'api-doc' 'sign-up' %}" class="form-control">Consigue tu Clave</a>
        {% endif %}
      </p>
      <hr class="mb-4">
      {% for category in endpoints_categories %}
      <h2><b>{{category.title}}</b></h2>
      {% for endpoint in category.endpoints.all %}
      {% if endpoint.is_available is True %}
      <div class="row mt-4 mb-4">
        <div class="col-12">
            <h5 id="{{endpoint.slug}}">
                <b>{{endpoint.title}}</b>
                {% if endpoint.is_premium %}
                <span class="badge badge-pill badge-xs bg-yellow">Premium</span>
                {% elif endpoint.is_deprecated %}
                <span class="badge badge-pill badge-xs bg-danger">Deprecated</span>
                {% endif %}
            </h5>            
        </div>
        <div class="col-xl-6 col-sm-12">
            <button class="form-control" id="{{endpoint.id}}" style="background-color: #dfdfdfaf;word-break: break-all;" onclick="copyToClipboard('#{{endpoint.id}}')"
            data-bs-toggle="popover" data-bs-placement="top" 
            data-bs-content="Copiar"><strong>{{endpoint.final_url}}?api_key={{key}}{{endpoint.continuation_url}}</strong></button>
          <p class="mt-4">
            <b>{{endpoint.description}}</b>
          </p>
        </div>
        <div class="col-xl-6 col-sm-12">
          <textarea style="height: 300px; font-size: 12px;background-color: #dfdfdfaf; color: black" class="form-control" readonly>
            {{ endpoint.example | safe }}
          </textarea>
        </div>
      </div>
      {% endif %}
      {% endfor %}
      <hr>
      {% endfor %}
      <script>
        function copyToClipboard(element) {
         var $temp = $("<input>");
         $("body").append($temp);
         $temp.val($(element).text()).select();
         document.execCommand("copy");
         $temp.remove();
       }
         </script>
{% endblock FirstContent%}

src/web/templates/explorar/inicio.html
{% extends "bases/base_content.html" %}
{% load static i18n extra %}
{% block header %}{% include "explorar/header/inicio.html" %}{% endblock header%}
{% block FirstCtaContent %}
{% include "explorar/cta/first.html" %}
{% endblock FirstCtaContent %}
{% block FirstContent %}
{% include "explorar/complements/first_content.html" %}
{% endblock FirstContent%}
{% block LeftSide %}

{% endblock LeftSide %}
{% block RightSide %}
{% include "explorar/side/inicio.html" %}
{% endblock RightSide %}
{% block MiddleCtaContent %}
{% include "explorar/cta/middle.html" %}
{% endblock MiddleCtaContent %}
{% block ListContinuation %}

{% endblock ListContinuation %}