config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views import defaults as default_views

from src.api.views import obtain_auth_key
from src.seo.sitemaps import (
    CompanySitemap,
    PublicBlogSitemap,
    QuestionSitemap,
    SuperinvestorSitemap,
    TermSitemap,
)
from src.general.views import Handler404

sitemaps = {
    "blogs": PublicBlogSitemap,
    "preguntas": QuestionSitemap,
    "empresas": CompanySitemap,
    "glosario": TermSitemap,
    "superinversores": SuperinvestorSitemap,
}

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path(
        settings.SECOND_ADMIN_URL, include("admin_honeypot.urls", namespace="admin_honeypot")
    ),
    path("", include("src.general.urls", namespace="general")),
    path("", include("src.web.urls", namespace="web")),
    path("", include("src.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("src.preguntas_respuestas.urls", namespace="preguntas_respuestas")),
    path("", include("src.escritos.urls", namespace="escritos")),
    path("", include("src.public_blog.urls", namespace="public_blog")),
    path("screener/", include("src.screener.urls", namespace="screener")),
    path("", include("src.super_investors.urls", namespace="super_investors")),
    path("", include("src.empresas.urls", namespace="empresas")),
    path("", include("src.socialmedias.urls", namespace="socialmedias")),
    path("", include("src.cartera.urls", namespace="cartera")),
    path("", include("src.seo.urls", namespace="seo")),
    path("", include("src.roboadvisor.urls", namespace="roboadvisor")),
    path("", include("src.business.urls", namespace="business")),
    path("", include("src.recsys.urls", namespace="recsys")),
    path("", include("src.emailing.urls", namespace="emailing")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("src.api.urls")),
    # DRF auth token
    path("api/obtener-clave/", obtain_auth_key),
]

handler403 = "src.general.views.handler403"
handler404 = Handler404.as_view()
handler500 = "src.general.views.handler500"

if settings.DEBUG:
    if "drf_spectacular" in settings.INSTALLED_APPS:
        from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

        urlpatterns += [
            path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
            path(
                "api/docs/",
                SpectacularSwaggerView.as_view(url_name="api-schema"),
                name="api-docs",
            ),
        ]

    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

src/api/urls.py
from django.conf import settings
from django.urls import include, path

from src.api.views import (
    APIDocumentation,
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
    request_API_key,
)

API_version = settings.API_VERSION["CURRENT_VERSION"]

app_name = "api"
urlpatterns = [
    path(f"{API_version}/", include("src.general.api.urls")),
    path(f"{API_version}/", include("src.screener.api.urls")),
    path(f"{API_version}/", include("src.public_blog.api.urls")),
    path(f"{API_version}/", include("src.notifications.api.urls")),
    path(f"{API_version}/", include("src.escritos.api.urls")),
    path(f"{API_version}/", include("src.empresas.api.urls")),
    path(f"{API_version}/", include("src.super_investors.api.urls")),
    path(f"{API_version}/", include("src.industries_sectors.api.urls")),
    path(f"{API_version}/", include("src.users.api.urls")),
    path(f"{API_version}/", include("src.cartera.api.urls")),
    path("request-api-key/", request_API_key, name="request_api_key"),
    path("api-documentacion/", APIDocumentation.as_view(), name="api_documentation"),
    path(f"{API_version}/jwt-token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path(f"{API_version}/jwt-token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path(
        f"{API_version}/jwt-token/refresh/",
        TokenRefreshView.as_view(),
        name="token_refresh",
    ),
]

src/business/urls.py
from django.urls import path

from .views import (
    CheckoutRedirectView,
    CreateCheckoutView,
    ProductDetailView,
    ProductsListView,
)
from .webhooks import stripe_webhook

app_name = "business"
urlpatterns = [
    path(
        "las-mejores-herramientas-para-invertir/",
        ProductsListView.as_view(),
        name="all_products",
    ),
    path(
        "la-mejor-herramienta-para-invertir-es/<slug>/",
        ProductDetailView.as_view(),
        name="product",
    ),
    path("create-checkout/<pk>/", CreateCheckoutView.as_view(), name="create_checkout"),
    path("pago-correcto/", CheckoutRedirectView.as_view(), name="order_success"),
    path("984dfgDFH68sDFg68s7fd", stripe_webhook, name="stripe_webhook"),
]

src/escritos/urls.py
from django.urls import path

from .views import (
    GlosarioView,
    ManageUserTermCorrectionDetailView,
    ManageUserTermCorrectionListView,
    TermCorrectionView,
    TermDetailsView,
)

app_name = "escritos"
urlpatterns = [
    path("diccionario-financiero/", GlosarioView.as_view(), name="glosario"),
    path("definicion/<slug>/", TermDetailsView.as_view(), name="single_term"),
    path("correction/<pk>", TermCorrectionView.as_view(), name="correction_term"),
    path(
        "users-corrections-to-review/",
        ManageUserTermCorrectionListView.as_view(),
        name="manage_all_corrections",
    ),
    path(
        "correction-to-review/<pk>/",
        ManageUserTermCorrectionDetailView.as_view(),
        name="manage_user_correction",
    ),
]

src/web/urls.py
from django.urls import path

from src.web.api.urls import urlpatterns as api_urlpatterns
from src.web.views import (
    AutomaticEmailNewsletterView,
    ExcelRedirectView,
    HomePage,
    LegalPages,
    ManageEmailEngagementCreateView,
    ManageEmailEngagementListView,
    ManageEmailEngagementUpdateView,
    ManagePreviewEmailEngagementDetailsView,
    ManageTermListView,
    ManageTermUpdateView,
    ManageWebView,
    RoadmapDetailView,
    RoadmapListView,
    SupportFormView,
)

app_name = "web"
urlpatterns = [
    path("", HomePage.as_view(), name="inicio"),
    path("asuntos-legales/<slug>/", LegalPages.as_view(), name="asuntos_legales"),
    path("excel-analisis/", ExcelRedirectView.as_view(), name="excel"),
    path("soporte/", SupportFormView.as_view(), name="soporte"),
    path("manage-web/", ManageWebView.as_view(), name="manage_web"),
    path("roadmap/", RoadmapListView.as_view(), name="roadmap"),
    path("roadmap-item/<slug>/", RoadmapDetailView.as_view(), name="roadmap_item"),
    path(
        "manage-list-emails-engament/",
        ManageEmailEngagementListView.as_view(),
        name="list_emails_engagement",
    ),
    path(
        "manage-create-email-engament/",
        ManageEmailEngagementCreateView.as_view(),
        name="create_email_engagement",
    ),
    path(
        "manage-update-email-engament/<pk>/",
        ManageEmailEngagementUpdateView.as_view(),
        name="update_email_engagement",
    ),
    path(
        "manage-preview-email-engament/<pk>/",
        ManagePreviewEmailEngagementDetailsView.as_view(),
        name="preview_email_engagement",
    ),
    path("manage-terms/", ManageTermListView.as_view(), name="manage_all_terms"),
    path("manage-term/<slug>/", ManageTermUpdateView.as_view(), name="manage_single_term"),
    path(
        "automatic-newsletter-creation/",
        AutomaticEmailNewsletterView.as_view(),
        name="automatic_creation_newsletter",
    ),
] + api_urlpatterns

src/web/templates/complements/footer.html
{% load static i18n extra %}
<footer class="footer section bg-primary text-white overflow-hidden">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 mb-4 mb-lg-0">
                <a class="footer-brand mr-lg-5 d-flex" href="{% url 'web:inicio' %}">
                    <img src="{% static 'general/assets/img/general/inversionesyfinanzas.WebP' %}" height="35"
                        class="mr-3" alt="Footer logo">
                </a>
                <p class="my-4">Una comunidad y todos los recursos que todo inversor necesita para mejorar sus
                    rendimientos.</p>
                <div class="mb-4 mb-lg-0">
                    <a href="https://www.facebook.com/InversionesyFinanzas" target="_blank" class="btn btn-white mr-1">
                        <i class="fab fa-facebook text-primary"></i>
                    </a>
                    <a href="https://twitter.com/InvFinz" target="_blank" class="btn btn-white mr-1">
                        <i class="fab fa-twitter text-primary"></i>
                    </a>
                    <a href="https://www.tiktok.com/@inversionesyfinanzas" target="_blank" class="btn btn-white mr-1">
                        <i class="fab fa-tiktok"></i>
                    </a>
                    <a href="https://www.youtube.com/channel/UCLC5OpaeNlcUyIKHFOXRlpw?sub_confirmation=1"
                        target="_blank" class="btn btn-white mr-1">
                        <i class="fab fa-youtube text-danger"></i>
                    </a>
                    <a href="https://www.instagram.com/inversiones.finanzas/" target="_blank"
                        class="btn btn-white mr-1">
                        <i class="fab fa-instagram text-danger"></i>
                    </a>
                </div>
            </div>
            <div class="col-6 col-sm-3 col-lg-2 mb-4 mb-lg-0">
                <h6>Información</h6>
                <ul class="links-vertical">
                    <li>
                        <a
                            href="{% url 'escritos:glosario' %}{% utm content='footer' term='Glosario' medium='web' source='invfin' campaign='website-links' %}">
                            Glosario
                        </a>
                    </li>
                    <li>
                        <a
                            href="{% url 'screener:screener_inicio' %}{% utm content='footer' term='Empresas' medium='web' source='invfin' campaign='website-links' %}">
                            Empresas
                        </a>

                    <li>
                        <a
                            href="{% url 'preguntas_respuestas:list_questions' %}{% utm content='footer' term='Preguntas' medium='web' source='invfin' campaign='website-links' %}">
                            Preguntas
                        </a>
                    </li>
                    <li>
                        <a
                            href="{% url 'public_blog:blog_list' %}{% utm content='footer' term='Escritores' medium='web' source='invfin' campaign='website-links' %}">
                            Escritores
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-6 col-sm-3 col-lg-2 mb-4 mb-lg-0">
                <h6>Herramientas</h6>
                <ul class="links-vertical">
                    <li>
                        <a
                            href="{% url 'business:all_products' %}{% utm content='footer' term='Excel' medium='web' source='invfin' campaign='website-links' %}">
                            Excels
                        </a>
                    </li>
                    <li>
                        <a
                            href="{% url 'roboadvisor:roboadvisor' %}{% utm content='footer' term='roboadvisor' medium='web' source='invfin' campaign='website-links' %}">
                            Roboadvisor
                        </a>
                    </li>
                    <li>
                        <a
                            href="{% url 'api:api_documentation' %}{% utm content='footer' term='api_documentation' medium='web' source='invfin' campaign='website-links' %}">
                            Documentación API
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-6 col-sm-3 col-lg-2 mb-4 mb-lg-0">
                <h6>Ayuda</h6>
                <ul class="links-vertical">
                    <li>
                        <a
                            href="{% url 'web:soporte' %}{% utm content='footer' term='Contáctanos' medium='web' source='invfin' campaign='website-links' %}">
                            Contáctanos
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-6 col-sm-3 col-lg-2 mb-4 mb-lg-0">
                <h6>Legales</h6>
                <ul class="links-vertical">
                    {% for link in legal_links %}
                    <li>
                        <a
                            href="{{link.get_absolute_url}}{% utm content='footer' term=legal.title medium='web' source='invfin' campaign='website-links' %}">
                            {{link.title}}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <hr class="my-4 my-lg-5">
        <div class="row">
            <div class="col pb-4 mb-md-0">
                <div class="d-flex text-center justify-content-center align-items-center">
                    <p class="font-weight-normal mb-0">© Inversiones & Finanzas <span class="current-year"></span>. All
                        rights reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

src/web/templates/complements/web_intro_base.html
{% extends "bases/shared_source.html" %}
{% block meta %}{% include "meta/meta.html" %}{% endblock meta %}
{% block css %}{% include "complements/web_intro_styling.html" %}{% endblock css %}


{% block MasterBody %}
{% block navbar %}{% include "complements/web_intro_navbar.html" %}{% endblock navbar%}
{% block content %}{% endblock content%}
{% block modal %}{% endblock modal %}
{% block footer %}{% include "complements/footer.html" %}{% endblock footer %}
<!-- {% block inline_javascript %}    
<script>
window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
</script>
{% endblock inline_javascript %} -->
{% block javascript %}{% include "complements/web_intro_scripts.html" %}{% endblock javascript %}
{% endblock MasterBody %}

src/web/templates/complements/web_intro_navbar.html
{% load static i18n extra %}
<header class="header-global">
    <nav id="navbar-main"
        class="navbar navbar-main navbar-expand-lg headroom py-lg-3 px-lg-6 navbar-light navbar-theme-primary">
        <div class="container">
            <a class="navbar-brand @@logo_classes"
                href="{% url 'web:inicio' %}{% utm 'navbar' 'inicio' 'web-principal' %}">
                <img class="navbar-brand-dark common"
                    src="{% static 'general/assets/img/general/finanzaseinversiones.WebP' %}" height="35"
                    alt="Logo light">
                <img class="navbar-brand-light common"
                    src="{% static 'general/assets/img/general/finanzaseinversiones.WebP' %}" height="35"
                    alt="Logo dark">
            </a>
            <div class="navbar-collapse collapse" id="navbar_global">
                <div class="navbar-collapse-header">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a href="{% url 'web:inicio' %}{% utm 'navbar' 'inicio' 'web-principal' %}">
                                <img src="{% static 'general/assets/img/general/finanzaseinversiones.WebP' %}"
                                    height="35" alt="Logo">
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <a href="#navbar_global" role="button" class="fas fa-times" data-toggle="collapse"
                                data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false"
                                aria-label="Toggle navigation"></a>
                        </div>
                    </div>
                </div>
                <ul class="navbar-nav navbar-nav-hover justify-content-center">
                    <li class="nav-item">
                        <a href="{% url 'screener:screener_inicio' %}{% utm 'navbar' 'screener' 'web-principal' %}"
                            class="nav-link">Análisis Empresas</a>
                    </li>
                    <li class="nav-item">
                        <a href="
                        {% url 'preguntas_respuestas:list_questions' %}{% utm 'navbar' 'Preguntas' 'web-principal' %}"
                            class="nav-link">Preguntas</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'escritos:glosario' %}{% utm 'navbar' 'Diccionario' 'web-principal' %}"
                            class="nav-link">Diccionario</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'roboadvisor:roboadvisor' %}{% utm 'navbar' 'Roboadvisor' 'web-principal' %}"
                            class="nav-link">Roboadvisor</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'business:all_products' %}{% utm 'navbar' 'Herramientas' 'web-principal' %}"
                            class="nav-link">Herramientas</a>
                    </li>
                </ul>
            </div>
            <div class="d-none d-lg-block @@cta_button_classes">
                <a href="{% url 'web:roadmap' %}{% utm 'navbar' 'roadmap' 'web-principal' %}"
                    class="btn btn-md btn-invfin-gold animate-up-2 mr-3"><i class="fas fa-th-large mr-2"></i>Roadmap</a>
                <a href="{% url 'account_login' %}{% utm 'navbar' 'direct' 'web-principal' %}"
                    class="btn btn-md btn-invfin-gold animate-up-2"><i class="fas fa-paper-plane mr-2"></i>Entrar</a>
            </div>
            <div class="d-flex d-lg-none align-items-center">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global"
                    aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
            </div>
        </div>
    </nav>
</header>

src/web/templates/complements/web_intro_scripts.html
{% load static %}

<!-- 
<script src="{% static 'general/assets/vendor/jquery/dist/jquery.min.js' %}"></script> -->
<script src="{% static 'general/assets/vendor/popper.js/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'general/assets/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'general/assets/vendor/headroom.js/dist/headroom.min.js' %}"></script>

<script src="{% static 'general/assets/vendor/onscreen/dist/on-screen.umd.min.js' %}"></script>
<script src="{% static 'general/assets/vendor/waypoints/lib/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'general/assets/vendor/jarallax/dist/jarallax.min.js' %}"></script>
<script src="{% static 'general/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>

<script src="{% static 'web_principal/assets/js/front.js' %}"></script>

src/web/templates/complements/web_intro_styling.html
{% load static %}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link type="text/css" href="{% static 'general/assets/vendor/prismjs/themes/prism.css' %}" rel="stylesheet">

<!-- Front CSS -->
<link type="text/css" href="{% static 'web_principal/css/front.css' %}" rel="stylesheet">